disabled_rules: # rule identifiers to exclude from running
  - nesting
  - identifier_name
  - large_tuple
  - implicit_return # Re-enable when we drop support for Swift 4.2
  - statement_position

statement_position:
  statement_mode: uncuddled_else

function_body_length:
  - 75 # warning

line_length:
  - 120

file_length:
  warning: 500
  error: 1200

opt_in_rules:
  - anyobject_protocol
  - identical_operands
  - implicit_return
  - last_where
  - legacy_random
  - operator_usage_whitespace
  - redundant_objc_attribute
  - sorted_imports
  - static_operator
  - toggle_bool
  - unused_control_flow_label
  - vertical_whitespace
  - force_unwrapping

force_cast: warning

force_try:
  severity: warning

trailing_comma:
  mandatory_comma: true